<?php

use App\Enums\OrderStatus;

return [
    "constants" => [
        'DEFAULT_PASSWORD' => 'Password@1234',
    ],
    "order_status_type" => [
        "for_bosta" => [
            OrderStatus::PickupRequested->value,
            OrderStatus::WaitingForRoute->value,
            OrderStatus::RouteAssigned->value,
            OrderStatus::PickedUpFromBusiness->value,
            OrderStatus::PickingUpFromConsignee->value,
            OrderStatus::PickedUpFromConsignee->value,
            OrderStatus::ReceivedAtWarehouse->value,
            OrderStatus::InTransitBetweenHubs->value,
            OrderStatus::PickingUp->value,
            OrderStatus::PickedUp->value,
            OrderStatus::PendingCustomerSignature->value,
            OrderStatus::DebriefedSuccessfully->value,
            OrderStatus::Delivered->value,
            OrderStatus::ReturnedToBusiness->value,
            OrderStatus::Exception->value,
            OrderStatus::Terminated->value,
            OrderStatus::CanceledUncoveredArea->value,
            OrderStatus::CollectionFailed->value,
            OrderStatus::Lost->value,
            OrderStatus::Damaged->value,
            OrderStatus::Investigation->value,
            OrderStatus::AwaitingYourAction->value,
            OrderStatus::Archived->value,
            OrderStatus::OnHold->value,
        ],
        "for_all_orders" => [
            OrderStatus::UnderProcessing->value,
            OrderStatus::Created->value,
            OrderStatus::WaitingForPayment->value,
            OrderStatus::ShippingCreates->value,
            OrderStatus::Preparing->value,
            OrderStatus::WaitingForQualityCheck->value,
            OrderStatus::Shipped->value,
            OrderStatus::WaitingForApproval->value,
            OrderStatus::Prepared->value,
            OrderStatus::Approved->value,
            OrderStatus::Rejected->value,
            OrderStatus::WaitingForContact->value,
            OrderStatus::CancellationRequested->value,
            OrderStatus::CancellationApproved->value,
            OrderStatus::CancellationRejected->value,
            OrderStatus::UnderEditing->value,
            OrderStatus::EditRequested->value,
            OrderStatus::EditApproved->value,
            OrderStatus::EditRejected->value,
            OrderStatus::UnderReturning->value,
            OrderStatus::ReturnRequested->value,
            OrderStatus::ReturnApproved->value,
            OrderStatus::ReturnRejected->value,
            OrderStatus::WaitingForRefund->value,
            OrderStatus::Delivered->value,
        ],
        "for_new_orders" => [
            OrderStatus::WaitingForPayment->value,
            OrderStatus::ShippingCreates->value,
            OrderStatus::WaitingForApproval->value,
            OrderStatus::Approved->value,
            OrderStatus::Rejected->value,
            OrderStatus::WaitingForContact->value,
        ],
        "for_approved_orders" => [
            OrderStatus::Preparing->value,
            OrderStatus::WaitingForQualityCheck->value,
            OrderStatus::Prepared->value,
            OrderStatus::Shipped->value,
        ],
    ]
];
